import type { Category, HomeDB, Project, RecurringTask } from "./types";

/** Days ago -> ISO date string */
function ago(days: number): string {
  return new Date(Date.now() - days * 86400000).toISOString().slice(0, 10);
}

/** Hours ago -> full ISO timestamp (for updatedAt attribution) */
function agoTime(hours: number): string {
  return new Date(Date.now() - hours * 3600000).toISOString();
}

export const SEED_CATEGORIES: Category[] = [
  { id: "yard", name: "Yard", slug: "yard", zone: "outdoor", sort: 1 },
  { id: "outside", name: "Outside", slug: "outside", zone: "outdoor", sort: 2 },
  { id: "kitchen", name: "Kitchen", slug: "kitchen", zone: "indoor", sort: 3 },
  { id: "bathrooms", name: "Bathrooms", slug: "bathrooms", zone: "indoor", sort: 4 },
  { id: "living-room", name: "Living Room", slug: "living-room", zone: "indoor", sort: 5 },
  { id: "office-mel", name: "Office · Mel", slug: "office-mel", zone: "indoor", sort: 6 },
  { id: "office-nate", name: "Office · Nate", slug: "office-nate", zone: "indoor", sort: 7 },
  { id: "entry-room", name: "Entry Room", slug: "entry-room", zone: "indoor", sort: 8 },
  { id: "garage", name: "Garage", slug: "garage", zone: "indoor", sort: 9 },
  { id: "master-bedroom", name: "Master Bedroom", slug: "master-bedroom", zone: "indoor", sort: 10 },
  { id: "house-repairs", name: "House Repairs", slug: "house-repairs", zone: "repairs", sort: 11 },
];

const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=70`;

export const SEED_PROJECTS: Project[] = [
  {
    id: "p-deck",
    title: "Composite deck extension",
    description:
      "Extend the back deck by 12 feet with composite boards, hidden fasteners, and a cable railing. Adds an outdoor dining zone off the kitchen slider.",
    categoryId: "yard",
    rank: 1,
    status: "in_progress",
    estimatedCost: 4800,
    spent: 2350,
    progress: 45,
    storeName: "Home Depot",
    storeUrl: "https://www.homedepot.com/b/Lumber-Composite-Decking-Composite-Deck-Boards/N-5yc1vZbqm4",
    inspirationImage: img("photo-1591825729269-caeb344f6df2"),
    beforeImage: img("photo-1600585154340-be6161a56a0c"),
    hotspot: { x: -0.9, y: 0.35, z: -1.8 },
    priceHistory: [
      { date: ago(120), price: 5400, note: "First quote" },
      { date: ago(75), price: 5150 },
      { date: ago(40), price: 4950, note: "Spring sale" },
      { date: ago(10), price: 4800, note: "Memorial Day pricing" },
    ],
    notes: [
      {
        id: "n-deck-1",
        author: "Nate",
        text: "Measured the run this weekend — 12'4\" to the fence line, so we're good on setback. Footings need to clear the sprinkler main on the east side.",
        createdAt: agoTime(50),
      },
      {
        id: "n-deck-2",
        author: "Melanie",
        text: "I like the cable railing in the inspiration pic way more than balusters. Adds ~$600 but worth it for the view.",
        createdAt: agoTime(6),
      },
    ],
    items: [
      { id: "i-deck-1", name: "Composite deck boards (24)", price: 2896, url: "https://www.homedepot.com/b/Lumber-Composite-Decking-Composite-Deck-Boards/N-5yc1vZbqm4", purchased: true },
      { id: "i-deck-2", name: "Cable railing kit, 40 ft", price: 645, url: "https://www.homedepot.com/s/cable%20railing%20kit", purchased: false },
      { id: "i-deck-3", name: "Joist tape + hidden fasteners", price: 168, url: "https://www.homedepot.com/s/deck%20hidden%20fasteners", purchased: true },
      { id: "i-deck-4", name: "Concrete footings (6)", price: 210, url: "https://www.homedepot.com/s/concrete%20deck%20footing", purchased: false },
    ],
    createdAt: ago(140),
    updatedBy: "Nate",
    updatedAt: agoTime(2),
  },
  {
    id: "p-countertops",
    title: "Quartz kitchen countertops",
    description:
      "Replace laminate with honed quartz in Calacatta Laza, waterfall edge on the island, and a matching full-height backsplash behind the range.",
    categoryId: "kitchen",
    rank: 2,
    status: "planned",
    estimatedCost: 6200,
    spent: 0,
    progress: 0,
    storeName: "Cambria via Lowe's",
    storeUrl: "https://www.lowes.com/pl/kitchen-countertops-accessories/quartz-countertops/4294515760",
    inspirationImage: img("photo-1556911220-bff31c812dba"),
    beforeImage: img("photo-1600489000022-c2086d79f9d4"),
    hotspot: { x: -0.9, y: 0.62, z: -1.28 },
    priceHistory: [
      { date: ago(90), price: 6900, note: "Showroom quote" },
      { date: ago(55), price: 6550 },
      { date: ago(20), price: 6200, note: "Contractor referral discount" },
    ],
    notes: [
      {
        id: "n-counter-1",
        author: "Melanie",
        text: "Showroom visit booked for Saturday 10am. Bring the cabinet door for color matching!",
        createdAt: agoTime(28),
      },
    ],
    items: [
      { id: "i-ct-1", name: "Calacatta Laza quartz slabs", price: 4980, url: "https://www.lowes.com/pl/kitchen-countertops-accessories/quartz-countertops/4294515760", purchased: false },
      { id: "i-ct-2", name: "Undermount workstation sink", price: 489, url: "https://www.lowes.com/pl/kitchen-sinks/4294736221", purchased: false },
      { id: "i-ct-3", name: "Backsplash panel cut", price: 731, purchased: false },
    ],
    createdAt: ago(95),
    updatedBy: "Melanie",
    updatedAt: agoTime(26),
  },
  {
    id: "p-shower",
    title: "Primary bath walk-in shower",
    description:
      "Convert the tub to a curbless walk-in shower with large-format porcelain, a linear drain, and a rainfall head. Niche with LED strip.",
    categoryId: "bathrooms",
    rank: 3,
    status: "idea",
    estimatedCost: 7400,
    spent: 0,
    progress: 0,
    storeName: "Floor & Decor",
    storeUrl: "https://www.flooranddecor.com/",
    inspirationImage: img("photo-1552321554-5fefe8c9ef14"),
    hotspot: { x: 1.05, y: 1.6, z: 0.0 },
    priceHistory: [
      { date: ago(60), price: 7800 },
      { date: ago(25), price: 7400 },
    ],
    createdAt: ago(70),
    updatedBy: "Melanie",
    updatedAt: agoTime(78),
  },
  {
    id: "p-fireplace",
    title: "Fireplace feature wall",
    description:
      "Floor-to-ceiling fluted oak surround with a 60\" linear electric fireplace, hidden media conduit, and picture-light sconces.",
    categoryId: "living-room",
    rank: 4,
    status: "in_progress",
    estimatedCost: 2900,
    spent: 1100,
    progress: 35,
    storeName: "Wayfair",
    storeUrl: "https://www.wayfair.com/home-improvement/sb0/electric-fireplaces-c1876340.html",
    inspirationImage: img("photo-1600210492486-724fe5c67fb0"),
    beforeImage: img("photo-1600121848594-d8644e57abab"),
    hotspot: { x: -1.76, y: 0.62, z: 0.05 },
    priceHistory: [
      { date: ago(100), price: 3200 },
      { date: ago(45), price: 3050 },
      { date: ago(12), price: 2900, note: "Fireplace insert on sale" },
    ],
    createdAt: ago(110),
    updatedBy: "Nate",
    updatedAt: agoTime(5),
  },
  {
    id: "p-ev-charger",
    title: "EV charger install",
    description:
      "Level 2 wall charger on a dedicated 60A circuit, cable management dock, and a weatherproof exterior outlet for the driveway.",
    categoryId: "garage",
    rank: 5,
    status: "planned",
    estimatedCost: 1250,
    spent: 0,
    progress: 0,
    storeName: "Amazon",
    storeUrl: "https://www.amazon.com/s?k=level+2+ev+charger",
    inspirationImage: img("photo-1593941707882-a5bba14938c7"),
    hotspot: { x: 2.28, y: 0.45, z: 0.6 },
    priceHistory: [
      { date: ago(150), price: 1650 },
      { date: ago(95), price: 1480 },
      { date: ago(50), price: 1340 },
      { date: ago(7), price: 1250, note: "Lowest tracked — good time to buy" },
    ],
    notes: [
      {
        id: "n-ev-1",
        author: "Nate",
        text: "Panel has room for a 60A breaker — confirmed with the electrician. Install quote was $420 on top of the unit.",
        createdAt: agoTime(31),
      },
    ],
    items: [
      { id: "i-ev-1", name: "Level 2 wall charger (48A)", price: 649, url: "https://www.amazon.com/s?k=level+2+ev+charger+48a", purchased: false },
      { id: "i-ev-2", name: "60A breaker + 6AWG wire run", price: 420, purchased: false },
      { id: "i-ev-3", name: "Cable dock + weatherproof outlet", price: 181, url: "https://www.amazon.com/s?k=ev+cable+dock", purchased: false },
    ],
    createdAt: ago(160),
    updatedBy: "Nate",
    updatedAt: agoTime(30),
  },
  {
    id: "p-walkway",
    title: "Paver walkway & landscape lighting",
    description:
      "Curved paver path from the driveway to the back gate with low-voltage bollard lights and fresh mulch beds along the fence line.",
    categoryId: "yard",
    rank: 6,
    status: "idea",
    estimatedCost: 2100,
    spent: 0,
    progress: 0,
    storeName: "Lowe's",
    storeUrl: "https://www.lowes.com/pl/pavers-stepping-stones/4294612564",
    inspirationImage: img("photo-1558904541-efa843a96f01"),
    hotspot: { x: -0.35, y: 0.08, z: 2.1 },
    priceHistory: [
      { date: ago(40), price: 2250 },
      { date: ago(9), price: 2100 },
    ],
    createdAt: ago(48),
    updatedBy: "Melanie",
    updatedAt: agoTime(120),
  },
  {
    id: "p-front-door",
    title: "Cedar porch surround & house numbers",
    description:
      "Wrap the front porch posts in clear cedar, add a modern horizontal address plaque, and swap the porch light for a warm sconce pair.",
    categoryId: "outside",
    rank: 7,
    status: "planned",
    estimatedCost: 980,
    spent: 0,
    progress: 0,
    storeName: "Etsy",
    storeUrl: "https://www.etsy.com/search?q=modern+house+numbers",
    inspirationImage: img("photo-1580587771525-78b9dba3b914"),
    hotspot: { x: -0.35, y: 0.98, z: 1.27 },
    priceHistory: [
      { date: ago(30), price: 1050 },
      { date: ago(5), price: 980 },
    ],
    createdAt: ago(38),
  },
  {
    id: "p-mel-office",
    title: "Built-in desk wall — Mel",
    description:
      "Wall-to-wall built-in with a floating walnut desk, closed storage below, open shelving with picture lights, and a cork pin rail.",
    categoryId: "office-mel",
    rank: 8,
    status: "idea",
    estimatedCost: 3400,
    spent: 0,
    progress: 0,
    storeName: "IKEA + custom fronts",
    storeUrl: "https://www.ikea.com/us/en/rooms/home-office/",
    inspirationImage: img("photo-1593062096033-9a26b09da705"),
    hotspot: { x: -1.74, y: 1.62, z: -0.3 },
    priceHistory: [{ date: ago(21), price: 3400 }],
    createdAt: ago(26),
  },
  {
    id: "p-nate-office",
    title: "Acoustic panels & studio lighting — Nate",
    description:
      "PET felt acoustic panels in a staggered layout, bias lighting behind the monitors, and a ceiling-mounted key light for calls.",
    categoryId: "office-nate",
    rank: 9,
    status: "idea",
    estimatedCost: 760,
    spent: 0,
    progress: 0,
    storeName: "Amazon",
    storeUrl: "https://www.amazon.com/s?k=acoustic+panels",
    inspirationImage: img("photo-1598550476439-6847785fcea6"),
    priceHistory: [
      { date: ago(33), price: 820 },
      { date: ago(6), price: 760 },
    ],
    createdAt: ago(41),
  },
  {
    id: "p-mudroom",
    title: "Entry mudroom bench & hooks",
    description:
      "Board-and-batten wall with a white oak bench, shoe cubbies underneath, matte black hooks, and a slim console shelf with hidden outlets.",
    categoryId: "entry-room",
    rank: 10,
    status: "planned",
    estimatedCost: 1150,
    spent: 0,
    progress: 0,
    storeName: "Home Depot",
    storeUrl: "https://www.homedepot.com/b/Storage-Organization-Entryway-Furniture/N-5yc1vZ2fkp7cd",
    inspirationImage: img("photo-1600607687920-4e2a09cf159d"),
    hotspot: { x: 0.12, y: 0.45, z: 1.26 },
    priceHistory: [
      { date: ago(52), price: 1280 },
      { date: ago(14), price: 1150 },
    ],
    createdAt: ago(58),
    updatedBy: "Melanie",
    updatedAt: agoTime(96),
  },
  {
    id: "p-garage-storage",
    title: "Garage slat-wall storage system",
    description:
      "Full slat-wall panels on the long wall, overhead ceiling racks for bins, and a fold-down workbench. Everything off the floor.",
    categoryId: "garage",
    rank: 11,
    status: "done",
    estimatedCost: 1600,
    spent: 1540,
    progress: 100,
    storeName: "Costco",
    storeUrl: "https://www.costco.com/garage-storage.html",
    inspirationImage: img("photo-1558036117-15d82a90b9b1"),
    beforeImage: img("photo-1601055283742-8b27e81b5553"),
    afterImage: img("photo-1558036117-15d82a90b9b1"),
    hotspot: { x: 1.6, y: 0.75, z: 1.27 },
    priceHistory: [
      { date: ago(210), price: 1850 },
      { date: ago(170), price: 1700 },
      { date: ago(150), price: 1600, note: "Bought at this price" },
    ],
    createdAt: ago(220),
    updatedBy: "Nate",
    updatedAt: agoTime(700),
  },
  {
    id: "p-bedroom-wall",
    title: "Master bedroom accent wall & blackout",
    description:
      "Limewash accent wall behind the bed, floating nightstands with sconces, and motorized blackout roller shades on both windows.",
    categoryId: "master-bedroom",
    rank: 12,
    status: "idea",
    estimatedCost: 1900,
    spent: 0,
    progress: 0,
    storeName: "Smith & Noble",
    storeUrl: "https://www.smithandnoble.com/",
    inspirationImage: img("photo-1616594039964-ae9021a400a0"),
    hotspot: { x: 0.45, y: 1.62, z: 0.97 },
    priceHistory: [
      { date: ago(28), price: 2050 },
      { date: ago(3), price: 1900 },
    ],
    createdAt: ago(35),
    updatedBy: "Melanie",
    updatedAt: agoTime(50),
  },
  {
    id: "p-gutter-drainage",
    title: "Gutter drainage & foundation seal",
    description:
      "Bury downspout extensions 10 ft from the foundation, regrade the north bed, and seal the hairline crack in the basement wall.",
    categoryId: "house-repairs",
    rank: 13,
    status: "planned",
    estimatedCost: 850,
    spent: 0,
    progress: 0,
    storeName: "Menards",
    storeUrl: "https://www.menards.com/",
    inspirationImage: img("photo-1570129477492-45c003edd2be"),
    hotspot: { x: 1.15, y: 0.2, z: -1.32 },
    priceHistory: [
      { date: ago(45), price: 900 },
      { date: ago(11), price: 850 },
    ],
    createdAt: ago(50),
    updatedBy: "Nate",
    updatedAt: agoTime(200),
  },
  {
    id: "p-window-seal",
    title: "Reseal south-facing windows",
    description:
      "Replace weather stripping and exterior caulk on the three south windows that fog up. Check for failed glazing seals while at it.",
    categoryId: "house-repairs",
    rank: 14,
    status: "idea",
    estimatedCost: 240,
    spent: 0,
    progress: 0,
    storeName: "Ace Hardware",
    storeUrl: "https://www.acehardware.com/",
    inspirationImage: img("photo-1600607687939-ce8a6c25118c"),
    hotspot: { x: -0.7, y: 1.62, z: 0.97 },
    priceHistory: [{ date: ago(17), price: 240 }],
    createdAt: ago(19),
  },
];

export const SEED_TASKS: RecurringTask[] = [
  {
    id: "t-hvac",
    name: "HVAC air filter",
    detail: "20×25×1 MERV 13 — furnace closet",
    intervalDays: 90,
    lastDone: ago(82),
    icon: "wind",
  },
  {
    id: "t-fridge",
    name: "Fridge water filter",
    detail: "Whirlpool EDR1RXD1, kitchen fridge",
    intervalDays: 180,
    lastDone: ago(150),
    icon: "droplets",
  },
  {
    id: "t-softener",
    name: "Water softener salt",
    detail: "Two 40 lb bags, basement utility",
    intervalDays: 30,
    lastDone: ago(24),
    icon: "filter",
  },
  {
    id: "t-gutters",
    name: "Clean gutters",
    detail: "Front + back, check downspouts",
    intervalDays: 180,
    lastDone: ago(120),
    icon: "home",
  },
  {
    id: "t-smoke",
    name: "Smoke detector batteries",
    detail: "All 6 detectors, 9V lithium",
    intervalDays: 365,
    lastDone: ago(200),
    icon: "battery",
  },
  {
    id: "t-lawn",
    name: "Lawn fertilizer",
    detail: "Seasonal blend, front + back yard",
    intervalDays: 45,
    lastDone: ago(41),
    icon: "leaf",
  },
  {
    id: "t-dryer",
    name: "Dryer vent deep clean",
    detail: "Full duct run to exterior vent",
    intervalDays: 365,
    lastDone: ago(310),
    icon: "flame",
  },
  {
    id: "t-sump",
    name: "Sump pump test",
    detail: "Pour a bucket, confirm float + discharge",
    intervalDays: 90,
    lastDone: ago(70),
    icon: "wrench",
  },
];

export const SEED_ACTIVITY = [
  {
    id: "a-1",
    actor: "Melanie",
    action: "added_note" as const,
    targetId: "p-deck",
    targetTitle: "Composite deck extension",
    detail: "cable railing over balusters",
    createdAt: agoTime(6),
  },
  {
    id: "a-2",
    actor: "Nate",
    action: "logged_price" as const,
    targetId: "p-ev-charger",
    targetTitle: "EV charger install",
    detail: "$1,250 — lowest tracked",
    createdAt: agoTime(30),
  },
  {
    id: "a-3",
    actor: "Melanie",
    action: "updated_project" as const,
    targetId: "p-countertops",
    targetTitle: "Quartz kitchen countertops",
    detail: "edited details",
    createdAt: agoTime(26),
  },
  {
    id: "a-4",
    actor: "Nate",
    action: "changed_status" as const,
    targetId: "p-fireplace",
    targetTitle: "Fireplace feature wall",
    detail: "now In progress",
    createdAt: agoTime(52),
  },
  {
    id: "a-5",
    actor: "Melanie",
    action: "completed_task" as const,
    targetTitle: "Water softener salt",
    detail: "cycle restarted",
    createdAt: agoTime(80),
  },
  {
    id: "a-6",
    actor: "Nate",
    action: "changed_priority" as const,
    targetId: "p-deck",
    targetTitle: "Composite deck extension",
    detail: "moved to #1",
    createdAt: agoTime(96),
  },
];

export const SEED_HOME_INFO = {
  livableSqft: 2450,
  totalSqft: 3180,
  bedrooms: 4,
  bathrooms: 2.5,
  appliances: [
    {
      id: "ap-water-heater",
      name: "Water heater",
      detail: "Rheem Performance 50-gal gas tank",
      installedYear: 2016,
    },
    {
      id: "ap-furnace",
      name: "Furnace",
      detail: "Trane XR80 gas, 80k BTU",
      installedYear: 2012,
    },
    {
      id: "ap-ac",
      name: "A/C condenser",
      detail: "Lennox 13ACX, 3-ton",
      installedYear: 2012,
    },
    {
      id: "ap-softener",
      name: "Water softener",
      detail: "Whirlpool WHES40, 40k grain",
      installedYear: 2019,
    },
    {
      id: "ap-roof",
      name: "Roof",
      detail: "Architectural asphalt shingles",
      installedYear: 2015,
    },
  ],
};

export const SEED_DB: HomeDB = {
  categories: SEED_CATEGORIES,
  projects: SEED_PROJECTS,
  tasks: SEED_TASKS,
  budget: {
    monthlyBudget: 1500,
    projectFund: 9200,
  },
  activity: SEED_ACTIVITY,
  homeInfo: SEED_HOME_INFO,
};
